spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 47.111.99.207
    port: 6379
    password: d52cKyUm9jgbdie3YW4e
    valid: true
    database: 116
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
    serialization:
      fail-on-empty-beans: false

  jpa:
    # show-sql: true 测试使用,默认更改为false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    provider:
      document:
        name: DEMO
        path: csp.nhsoft.cn/demo
        version: 1.0
        target: C:/Users/86178/demo/demo.json
